apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv
  labels:
    app: consul
    type: pv-local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/tmp"
