 apiVersion: v1
 kind: Service
 metadata:
   name: consul-internal-load-balancer
   labels:
     app: consul
 spec:
   type: LoadBalancer
   ports:
     - name: http
       port: 8500
       protocol: "TCP"
     - name: https
       port: 8443
       protocol: "TCP"
     - name: serf-lan-tcp
       port: 8301
       protocol: "TCP"
     - name: server-rpc
       port: 8300
       protocol: "TCP"
   selector:
     app: consul
