apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-data
  labels:
    app: consul
    type: pv-local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/joy/workspace/personal/data-volume"
