apiVersion: apps/v1beta1
kind: Statefulset
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
  spec:
    containers:
    - image: mysql:5.6
      name: mysql
      env:
        # Use secret in real usage
      - name: MYSQL_ROOT_PASSWORD
        value: password
      ports:
      - containerPort: 3306
        name: mysql
      volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
    volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
    - name: config-map
      configMap:
        name: mysql
